arxiv:
  categories:
    - math.DS
    - math.PR
    - math.OC
    - math.NA
    - math.AP
    - cs.SY
    - cs.LG
    - stat.ML
    - stat.ME
    - physics.data-an
    - physics.comp-ph
    - nlin.AO
    - nlin.CD
    - nlin.SI
    - q-bio.QM

llm:
  model_name: 'glm-5.2'
